services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      chat:
        condition: service_healthy

  chat:
    build: ./chat
    ports:
      - "5001:5001"
    env_file:
      - ./chat/.env
    volumes:
      - ./chat/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  vector:
    build: ./vector
    ports:
      - "5002:5002"
    env_file:
      - ./vector/.env
    volumes:
      - ./rag_store:/app/rag_store

  ai:
    build: ./ai
    ports:
      - "5003:5003"
    env_file:
      - ./ai/.env

volumes:
  data:
  rag_store:
